project:
  type: website

website:
  title: "big_ref"
  site-url: "example.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
google-scholar: true

editor: visual

